### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by stonier** [rosjava/android_remocons#48]
Switching between running app, robot remocon app list and back again is causing it to go out of memory.

```
12-30 00:25:27.522    1452-3824/com.github.rosjava.android_remocons.robot_remocon E/dalvikvm-heap﹕ Out of memory on a 65552-byte allocation.
12-30 00:25:27.522    1452-3824/com.github.rosjava.android_remocons.robot_remocon I/dalvikvm﹕ "pool-33-thread-24" prio=5 tid=667 RUNNABLE
12-30 00:25:27.522    1452-3824/com.github.rosjava.android_remocons.robot_remocon I/dalvikvm﹕ | group="main" sCount=0 dsCount=0 obj=0x43ece310 self=0x6abc4098
12-30 00:25:27.522    1452-3824/com.github.rosjava.android_remocons.robot_remocon I/dalvikvm﹕ | sysTid=3824 nice=0 sched=0/0 cgrp=apps handle=1572155112
12-30 00:25:27.522    1452-3824/com.github.rosjava.android_remocons.robot_remocon I/dalvikvm﹕ | state=R schedstat=( 0 0 0 ) utm=28 stm=3 core=0
12-30 00:25:27.522    1452-3824/com.github.rosjava.android_remocons.robot_remocon I/dalvikvm﹕ at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
12-30 00:25:27.522    1452-3824/com.github.rosjava.android_remocons.robot_remocon I/dalvikvm﹕ at java.nio.MemoryBlock.allocate(MemoryBlock.java:126)
12-30 00:25:27.522    1452-3824/com.github.rosjava.android_remocons.robot_remocon I/dalvikvm﹕ at java.nio.ReadWriteDirectByteBuffer.<init>(ReadWriteDirectByteBuffer.java:46)
12-30 00:25:27.522    1452-3824/com.github.rosjava.android_remocons.robot_remocon I/dalvikvm﹕ at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:68)
12-30 00:25:27.522    1452-3824/com.github.rosjava.android_remocons.robot_remocon I/dalvikvm﹕ at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$Preallocation.<init>(SocketSendBufferPool.java:158)
12-30 00:25:27.522    1452-3824/com.github.rosjava.android_remocons.robot_remocon I/dalvikvm﹕ at org.jboss.netty.channel.socket.nio.SocketSendBufferPool.<init>(SocketSendBufferPool.java:40)
12-30 00:25:27.522    1452-3824/com.github.rosjava.android_remocons.robot_remocon I/dalvikvm﹕ at org.jboss.netty.channel.socket.nio.AbstractNioWorker.<init>(AbstractNioWorker.java:123)
12-30 00:25:27.522    1452-3824/com.github.rosjava.android_remocons.robot_remocon I/dalvikvm﹕ at org.jboss.netty.channel.socket.nio.NioWorker.<init>(NioWorker.java:44)
12-30 00:25:27.522    1452-3824/com.github.rosjava.android_remocons.robot_remocon I/dalvikvm﹕ at org.jboss.netty.channel.socket.nio.NioWorkerPool.createWorker(NioWorkerPool.java:34)
12-30 00:25:27.522    1452-3824/com.github.rosjava.android_remocons.robot_remocon I/dalvikvm﹕ at org.jboss.netty.channel.socket.nio.NioWorkerPool.createWorker(NioWorkerPool.java:26)
12-30 00:25:27.522    1452-3824/com.github.rosjava.android_remocons.robot_remocon I/dalvikvm﹕ at org.jboss.netty.channel.socket.nio.AbstractNioWorkerPool.<init>(AbstractNioWorkerPool.java:58)
12-30 00:25:27.522    1452-3824/com.github.rosjava.android_remocons.robot_remocon I/dalvikvm﹕ at org.jboss.netty.channel.socket.nio.NioWorkerPool.<init>(NioWorkerPool.java:29)
12-30 00:25:27.522    1452-3824/com.github.rosjava.android_remocons.robot_remocon I/dalvikvm﹕ at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.<init>(NioServerSocketChannelFactory.java:131)
12-30 00:25:27.522    1452-3824/com.github.rosjava.android_remocons.robot_remocon I/dalvikvm﹕ at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.<init>(NioServerSocketChannelFactory.java:115)
12-30 00:25:27.522    1452-3824/com.github.rosjava.android_remocons.robot_remocon I/dalvikvm﹕ at org.ros.internal.transport.tcp.TcpRosServer.start(TcpRosServer.java:78)
12-30 00:25:27.522    1452-3824/com.github.rosjava.android_remocons.robot_remocon I/dalvikvm﹕ at org.ros.internal.node.server.SlaveServer.start(SlaveServer.java:83)
12-30 00:25:27.522    1452-3824/com.github.rosjava.android_remocons.robot_remocon I/dalvikvm﹕ at org.ros.internal.node.DefaultNode.<init>(DefaultNode.java:150)
12-30 00:25:27.532    1452-3824/com.github.rosjava.android_remocons.robot_remocon I/dalvikvm﹕ at org.ros.node.DefaultNodeFactory.newNode(DefaultNodeFactory.java:41)
12-30 00:25:27.532    1452-3824/? I/dalvikvm﹕ at org.ros.node.DefaultNodeMainExecutor$2.run(DefaultNodeMainExecutor.java:139)
12-30 00:25:27.532    1452-3824/? I/dalvikvm﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
12-30 00:25:27.532    1452-3824/? I/dalvikvm﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
12-30 00:25:27.532    1452-3824/? I/dalvikvm﹕ at java.lang.Thread.run(Thread.java:856)
12-30 00:25:27.532    1452-3824/? I/dalvikvm﹕ [ 12-30 00:25:27.552  1902: 1932 I/ThermalDaemon ]
    Sensor 'tsens_tz_sensor9' - alarm cleared 1 at 60.0 degC
```

**Comment by stonier** [comment]
Happening in the dashboard...

```
 21548-21548/com.github.rosjava.android_remocons.robot_remocon E/ViewRootImpl﹕ sendUserActionEvent() mView == null
12-30 01:37:41.813  21548-23867/com.github.rosjava.android_remocons.robot_remocon E/dalvikvm-heap﹕ Out of memory on a 505152-byte allocation.
12-30 01:37:41.953  21548-23871/com.github.rosjava.android_remocons.robot_remocon E/dalvikvm-heap﹕ Out of memory on a 65552-byte allocation.
12-30 01:37:41.973  21548-23871/com.github.rosjava.android_remocons.robot_remocon E/AndroidRuntime﹕ FATAL EXCEPTION: pool-33-thread-27
    java.lang.OutOfMemoryError
            at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
            at java.nio.MemoryBlock.allocate(MemoryBlock.java:126)
            at java.nio.ReadWriteDirectByteBuffer.<init>(ReadWriteDirectByteBuffer.java:46)
            at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:68)
            at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$Preallocation.<init>(SocketSendBufferPool.java:158)
            at org.jboss.netty.channel.socket.nio.SocketSendBufferPool.<init>(SocketSendBufferPool.java:40)
            at org.jboss.netty.channel.socket.nio.AbstractNioWorker.<init>(AbstractNioWorker.java:123)
            at org.jboss.netty.channel.socket.nio.NioWorker.<init>(NioWorker.java:44)
            at org.jboss.netty.channel.socket.nio.NioWorkerPool.createWorker(NioWorkerPool.java:34)
            at org.jboss.netty.channel.socket.nio.NioWorkerPool.createWorker(NioWorkerPool.java:26)
            at org.jboss.netty.channel.socket.nio.AbstractNioWorkerPool.<init>(AbstractNioWorkerPool.java:58)
            at org.jboss.netty.channel.socket.nio.NioWorkerPool.<init>(NioWorkerPool.java:29)
            at org.jboss.netty.channel.socket.nio.NioClientSocketChannelFactory.<init>(NioClientSocketChannelFactory.java:149)
            at org.jboss.netty.channel.socket.nio.NioClientSocketChannelFactory.<init>(NioClientSocketChannelFactory.java:114)
            at org.ros.internal.transport.tcp.TcpClient.<init>(TcpClient.java:64)
            at org.ros.internal.transport.tcp.TcpClientManager.connect(TcpClientManager.java:67)
            at org.ros.internal.node.service.DefaultServiceClient.connect(DefaultServiceClient.java:135)
            at org.ros.internal.node.service.ServiceFactory.newClient(ServiceFactory.java:144)
            at org.ros.internal.node.DefaultNode.newServiceClient(DefaultNode.java:365)
            at org.ros.internal.node.DefaultNode.newServiceClient(DefaultNode.java:372)
            at com.github.rosjava.android_apps.application_management.AppManager.stopApp(AppManager.java:152)
            at com.github.rosjava.android_apps.application_management.AppManager.onStart(AppManager.java:205)
            at org.ros.internal.node.DefaultNode$5.run(DefaultNode.java:506)
            at org.ros.internal.node.DefaultNode$5.run(DefaultNode.java:503)
            at org.ros.concurrent.EventDispatcher.loop(EventDispatcher.java:43)
            at org.ros.concurrent.CancellableLoop.run(CancellableLoop.java:56)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
12-30 01:37:41.983      301-563/? E/SurfaceFlinger﹕ #### captureScreenImplLocked
12-30 01:37:42.033  21548-23867/com.github.rosjava.android_remocons.robot_remocon E/Dashboard﹕ Error during dashboard instantiation:
    java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at com.github.rosjava.android_apps.application_management.Dashboard.createDashboard(Dashboard.java:100)
            at com.github.rosjava.android_apps.application_management.Dashboard.createDashboard(Dashboard.java:117)
            at com.github.rosjava.android_apps.application_management.Dashboard.createDashboard(Dashboard.java:133)
            at com.github.rosjava.android_apps.application_management.Dashboard.onStart(Dashboard.java:171)
            at org.ros.internal.node.DefaultNode$5.run(DefaultNode.java:506)
            at org.ros.internal.node.DefaultNode$5.run(DefaultNode.java:503)
            at org.ros.concurrent.EventDispatcher.loop(EventDispatcher.java:43)
            at org.ros.concurrent.CancellableLoop.run(CancellableLoop.java:56)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
     Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class <unknown>
            at android.view.LayoutInflater.createView(LayoutInflater.java:619)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at com.github.rosjava.android_apps.application_management.dashboards.DefaultDashboard.inflateSelf(DefaultDashboard.java:78)
            at com.github.rosjava.android_apps.application_management.dashboards.DefaultDashboard.<init>(DefaultDashboard.java:70)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at com.github.rosjava.android_apps.application_management.Dashboard.createDashboard(Dashboard.java:100)
            at com.github.rosjava.android_apps.application_management.Dashboard.createDashboard(Dashboard.java:117)
            at com.github.rosjava.android_apps.application_management.Dashboard.createDashboard(Dashboard.java:133)
            at com.github.rosjava.android_apps.application_management.Dashboard.onStart(Dashboard.java:171)
            at org.ros.internal.node.DefaultNode$5.run(DefaultNode.java:506)
            at org.ros.internal.node.DefaultNode$5.run(DefaultNode.java:503)
            at org.ros.concurrent.EventDispatcher.loop(EventDispatcher.java:43)
            at org.ros.concurrent.CancellableLoop.run(CancellableLoop.java:56)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at android.view.LayoutInflater.createView(LayoutInflater.java:593)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at com.github.rosjava.android_apps.application_management.dashboards.DefaultDashboard.inflateSelf(DefaultDashboard.java:78)
            at com.github.rosjava.android_apps.application_management.dashboards.DefaultDashboard.<init>(DefaultDashboard.java:70)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at com.github.rosjava.android_apps.application_management.Dashboard.createDashboard(Dashboard.java:100)
            at com.github.rosjava.android_apps.application_management.Dashboard.createDashboard(Dashboard.java:117)
            at com.github.rosjava.android_apps.application_management.Dashboard.createDashboard(Dashboard.java:133)
            at com.github.rosjava.android_apps.application_management.Dashboard.onStart(Dashboard.java:171)
            at org.ros.internal.node.DefaultNode$5.run(DefaultNode.java:506)
            at org.ros.internal.node.DefaultNode$5.run(DefaultNode.java:503)
            at org.ros.concurrent.EventDispatcher.loop(EventDispatcher.java:43)
            at org.ros.concurrent.CancellableLoop.run(CancellableLoop.java:56)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
     Caused by: java.lang.OutOfMemoryError
            at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:596)
            at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
            at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:472)
            at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:502)
            at com.github.rosjava.android_extras.gingerbread.view.BatteryLevelView.init(BatteryLevelView.java:44)
            at com.github.rosjava.android_extras.gingerbread.view.BatteryLevelView.<init>(BatteryLevelView.java:35)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at android.view.LayoutInflater.createView(LayoutInflater.java:593)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at com.github.rosjava.android_apps.application_management.dashboards.DefaultDashboard.inflateSelf(DefaultDashboard.java:78)
            at com.github.rosjava.android_apps.application_management.dashboards.DefaultDashboard.<init>(DefaultDashboard.java:70)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at com.github.rosjava.android_apps.application_management.Dashboard.createDashboard(Dashboard.java:100)
            at com.github.rosjava.android_apps.application_management.Dashboard.createDashboard(Dashboard.java:117)
            at com.github.rosjava.android_apps.application_management.Dashboard.createDashboard(Dashboard.java:133)
            at com.github.rosjava.android_apps.application_management.Dashboard.onStart(Dashboard.java:171)
            at org.ros.internal.node.DefaultNode$5.run(DefaultNode.java:506)
            at org.ros.internal.node.DefaultNode$5.run(DefaultNode.java:503)
            at org.ros.concurrent.EventDispatcher.loop(EventDispatcher.java:43)
            at org.ros.concurrent.CancellableLoop.run(CancellableLoop.java:56)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
```
