### ISSUE TITLE
Run time exception error about no service

### ISSUE THREAD

**Issue by dwlee** [rosjava/android_remocons#49]
when we start the talker app, the app is died.
following error message

```
01-16 15:15:35.668   30529-2086/com.github.rosjava.android_remocons.robot_remocon D/ApplicationManagement﹕ start app service client created [/cybernetic_pirate/start_app]
01-16 15:15:35.743   30529-2086/com.github.rosjava.android_remocons.robot_remocon W/ApplicationManagement﹕ start app service not found [/cybernetic_pirate/start_app]
01-16 15:15:35.743   30529-2086/com.github.rosjava.android_remocons.robot_remocon W/dalvikvm﹕ threadid=86: thread exiting with uncaught exception (group=0x414df2a0)
01-16 15:15:35.743   30529-2086/com.github.rosjava.android_remocons.robot_remocon E/AndroidRuntime﹕ FATAL EXCEPTION: pool-21-thread-61
    org.ros.exception.RosRuntimeException: org.ros.exception.ServiceNotFoundException: No such service /cybernetic_pirate/start_app of type rocon_app_manager_msgs/StartApp
            at com.github.rosjava.android_apps.application_management.AppManager.startApp(AppManager.java:138)
            at com.github.rosjava.android_apps.application_management.AppManager.onStart(AppManager.java:203)
            at org.ros.internal.node.DefaultNode$5.run(DefaultNode.java:506)
            at org.ros.internal.node.DefaultNode$5.run(DefaultNode.java:503)
            at org.ros.concurrent.EventDispatcher.loop(EventDispatcher.java:43)
            at org.ros.concurrent.CancellableLoop.run(CancellableLoop.java:56)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)
     Caused by: org.ros.exception.ServiceNotFoundException: No such service /cybernetic_pirate/start_app of type rocon_app_manager_msgs/StartApp
            at org.ros.internal.node.DefaultNode.newServiceClient(DefaultNode.java:356)
            at org.ros.internal.node.DefaultNode.newServiceClient(DefaultNode.java:372)
            at com.github.rosjava.android_apps.application_management.AppManager.startApp(AppManager.java:134)
            at com.github.rosjava.android_apps.application_management.AppManager.onStart(AppManager.java:203)
            at org.ros.internal.node.DefaultNode$5.run(DefaultNode.java:506)
            at org.ros.internal.node.DefaultNode$5.run(DefaultNode.java:503)
            at org.ros.concurrent.EventDispatcher.loop(EventDispatcher.java:43)
            at org.ros.concurrent.CancellableLoop.run(CancellableLoop.java:56)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)
```

**Comment by stonier** [comment]
Irrelevant now after the update - no more app manager start app code.
